### ISSUE TITLE
Feature: don't throw exception for path already found in `sys.path`

### ISSUE THREAD

**Issue by alelom** [hirsimaki-markus/importmonkey#1]
WIth this library, it's easy to get `ValueError: The path 'C:\\....' is already found in sys.path`. I think that the role of this library should be to swallow this exception, as it is irrelevant and not useful when simplifying the `import`s procedure.

Repro example:

```
root
├─ subA
│   └─ subscriptA.py
├─ subB
│   └─ subscriptB.py
└─ rootscript.py
```

Content of `rootscript.py`:
```python
def somerootfunction(str):
    print("I'm a function at the root of the project. " + str)
```

Content of `subscriptA.py`:
```python
from importmonkey import add_path; add_path("../")
from rootscript import somerootfunction

def root_function_wrapper(str):
    somerootfunction("Invoked by root_function_wrapper in subscriptA. " + str)
```

Content of `subscriptB.py`:
```python
from importmonkey import add_path; add_path("../")
from subA.subscriptA import root_function_wrapper

root_function_wrapper("Invoked by subscriptB.")
```

If you run the code in `subscriptB.py`, you get the above exception. Wrapping the `add_path()` statement in a try-except block removes the issue. This error is irrelevant and should be swallowed by importmonkey.

**Comment by alelom** [comment]
I'd simply propose simplifying: 

https://github.com/hirsimaki-markus/importmonkey/blob/c127b49ea7e1cd8a573a51f884075173c07c4b03/src/importmonkey/__init__.py#L135-L139

to:

```python
sys.path.append(final_path_str) 
```

As this exception serves no purpose.

**Comment by hirsimaki-markus** [comment]
I agree with your reasoning about raising an error, although the check to see if a given path is already in `sys.path` should be retained to avoid polluting the path list if the function ends up being called repeatedly.

I will publish a 2.0.0 package to pip since this feels like a breaking change.

**Comment by hirsimaki-markus** [comment]
Resolved in https://github.com/hirsimaki-markus/importmonkey/commit/830d95b0f78a2b96cd785e711cd2941934e7f102
see https://pypi.org/project/importmonkey/2.0.0/ for release

**Comment by alelom** [comment]
Fantastic, thanks! It works beautfully now. 
I'll close #2 as non relevant anymore.

**Comment by hirsimaki-markus** [comment]
> Fantastic, thanks! It works beautfully now. I'll close #2 as non relevant anymore.

If you don't mind, how did you find importmonkey and, if you can disclose it, where do you use it?
