### ISSUE TITLE
Relative paths don't work in Jupyter notebooks

### ISSUE THREAD

**Issue by 0xDA41** [hirsimaki-markus/importmonkey#3]
In a Jupyter notebook, `__file__` is undefined, so importmonkey doesn't work with relative paths.

### Steps to recreate (using VSCode):
- Install the official Jupyter extension
- Create an `ipynb` notebook
- `print(__file__)`

### Proposed fix:

Adding a check to see if `__file__` exists, and if not, using `os.path.abspath('')` instead would fix this.

### Motivation

Normally one might say Jupyter is a very specific environment, and in a web-based notebook environment, one wouldn't need filesystem-based imports anyway.

In data science and ML, quite a few people are using notebooks locally via VSCode though, as it lets you work on notebooks and supporting libraries at the same time. In this setting, filesystem-based imports in notebooks make perfect sense.

### Current workaround example:
`add_path(f"{os.path.abspath('')}'/..")`

**Comment by hirsimaki-markus** [comment]
This will be fixed soon.

**Comment by hirsimaki-markus** [comment]
Can you provide me with an example project structure in your use case? I'm planning on using `os.getcwd()` as fallback when `__file__` is not present.

`f"{os.path.abspath('')}'/.."` seems to resolve one directory level higher than `os.getcwd()` if i understood your use case correctly.

**Comment by 0xDA41** [comment]
For example, in my generative art 'atelier' repository, I have a few local packages that I keep editing, so having them separate wouldn't make a lot of sense... but then I also want to group my ipynb notebooks that I use for prototyping and meanderings.

So, say...
```
- atelier
  +-algorithms
  |  +- __init__.py
  |  +- cellular.py
  |  +- supershapes.py
  |
  +- graphics
  |  +- __init__.py
  |  +- cairo-tools.py
  |  +- interpolation.py
  |
  +- 2024-summer
  |  +- some_project.ipynb
...
  +- 2023-autumn
  |  +- some_other_project.ipynb
```

And yes, `f"{os.path.abspath('')}'/.."` is 'the directory above cwd.'
Normally, if importmonkey was working correctly, I'd expect to write `add_path('..')` for the same effect.

The import part in my ipynbs might look like:
```
import numpy as np
from numba import jit, vectorize
import importmonkey
add_path('..') #currently add_path(f"{os.path.abspath('')}'/..")
from graphics import interpolation
from algorithms import supershapes
```

**Comment by hirsimaki-markus** [comment]
Resolved in 2.1.0 release.

**Comment by hirsimaki-markus** [comment]
@dani-corie There was small bug in 2.1.0. Use 2.1.1 instead.

Btw, how did you find this package?

**Comment by 0xDA41** [comment]
I googled simple ways to do path-relative imports, and it was mentioned on a stackoverflow page. ;)
